"""Declarative base and the column mixins shared by every ORM model."""

from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Root of the ORM class hierarchy; owns the metadata Alembic compares against."""


class TimestampMixin:
    """Adds the `created_at` audit column.

    The value is produced by the database (`now()`), not by Python, so that rows
    inserted by a migration or by hand get a timestamp too, and so every row is
    stamped by the same clock. The column is timezone-aware (`timestamptz`).
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )


class EntityMixin(TimestampMixin):
    """Adds a UUID primary key generated by the application, plus `created_at`.

    `uuid4` runs in Python at flush time rather than in the database, which keeps the
    id generation identical across every environment and avoids depending on a
    server-side uuid function. Entities whose primary key comes from outside
    (BlockWorkLog, whose id is generated by the mobile app so that an offline resend
    is idempotent) must use `TimestampMixin` and declare their own `id`.
    """

    id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
    )
